spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatapp_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

#Pourquoi les lignes springdoc : ? Elles ne sont pas obligatoires (Springdoc fonctionne avec des valeurs par defaut), mais les expliciter te permet de savoir exactement ou trouver l'interface (/swagger-ui.html) et la spec JSON brute (/v3/api-docs) plutot que de deviner.
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs